name = "Lean4"
version = "0.1.0"
defaultTargets = ["lean4"]

[[lean_lib]]
name = "Lean4"

[[lean_exe]]
name = "lean4"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"
